#define VK_ONE          49
#define VK_TWO          50
#define VK_THREE        51
#define VK_FOUR         52
#define VK_FIVE         53
#define VK_SIX          54
#define VK_SEVEN        55
#define VK_EIGHT        56
#define VK_NINE         57
#define VK_ZERO         58
#define VK_A	        65
#define VK_B            66
#define VK_C            67
#define VK_D            68
#define VK_E            69
#define VK_F            70
#define VK_G            71
#define VK_H            72
#define VK_I            73
#define VK_J            74
#define VK_K            75
#define VK_L            76
#define VK_M            77
#define VK_N            78
#define VK_O            79
#define VK_P            80
#define VK_Q            81
#define VK_R            82
#define VK_S            83
#define VK_T            84
#define VK_U            85
#define VK_V            86
#define VK_W            87
#define VK_X            88
#define VK_Y            89
#define VK_Z            90
#define VK_SEMICOLON    186
#define VK_EQUALS       187
#define VK_COMMA        188
#define VK_HYPHEN       189
#define VK_PERIOD       190
#define VK_FSLASH       191
#define VK_BACKTICK     192

#define VK_LEFTSQUARE   219
#define VK_BACKSLASH    220
#define VK_RIGHTSQUARE  221
#define VK_TICK         222

#define VK_EXCLAMATION  349
#define VK_ATSYM        350
#define VK_POUND        351
#define VK_DOLLAR       352
#define VK_PERCENT      353
#define VK_CARET        354
#define VK_AMP          355
#define VK_ASTERISK     356
#define VK_LPAREN       357
#define VK_RPAREN       358

#define VK_CAP_A	    365
#define VK_CAP_B        366
#define VK_CAP_C        367
#define VK_CAP_D        368
#define VK_CAP_E        369
#define VK_CAP_F        370
#define VK_CAP_G        371
#define VK_CAP_H        372
#define VK_CAP_I        373
#define VK_CAP_J        374
#define VK_CAP_K        375
#define VK_CAP_L        376
#define VK_CAP_M        377
#define VK_CAP_N        378
#define VK_CAP_O        379
#define VK_CAP_P        380
#define VK_CAP_Q        381
#define VK_CAP_R        382
#define VK_CAP_S        383
#define VK_CAP_T        384
#define VK_CAP_U        385
#define VK_CAP_V        386
#define VK_CAP_W        387
#define VK_CAP_X        388
#define VK_CAP_Y        389
#define VK_CAP_Z        390
#define VK_COLON        486
#define VK_PLUS         487
#define VK_LESSTHAN     488
#define VK_UNDERSCORE   489
#define VK_GREATERTHAN  490
#define VK_QUESTION     491

#define VK_LEFTCURLY    519
#define VK_PIPE         520
#define VK_RIGHTCURLY   521
#define VK_DOUBLEQUOTE  522
